apiVersion: v1
kind: Pod
metadata:
  name: pyweb
spec:
  containers:
    - image: docker.io/iyamoto/pyweb:test
      name: pyweb
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /ping
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      resources:
        requests:
          cpu: "100m"
          memory: "32Mi"
        limits:
          cpu: "5000m"
          memory: "64Mi"


