apiVersion: v1
kind: Pod
metadata:
  name: pyweb
spec:
  containers:
    - image: docker.io/iyamoto/pyweb:test
      name: pyweb
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
